#!/bin/bash

# Functions
has_flag() { echo true; }

# List configuration file fields
list_config() {
	# awk script ignores comments and new lines
	awk '{ if(substr($1, 1, 1) != "#" && substr($1, 1, 1) != '\n') print $1 ": " $2}' /home/$USER/.ssh-mounter.cfg;
}

# Create config file if non existant
if [ ! -f /home/$USER/.ssh-mounter.cfg ]; then
 	echo -e '# SSH-MOUNTER CONFIG -- EDIT USING COMMAND LINE TOOLS\n' > "/home/$USER/.ssh-mounter.cfg"
fi

case "$1" in
	-l)
		list_config
		;;
esac
